use FreelancerDb
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Social network 1', 500, 1, 5)
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Online market 1', 1500, 2, 5)
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Website 1', 100, 5, 1)
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Website 2', 300, 3, 2)
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Social network 2', 600, 1, 5)
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Social network 3', 700, 4, 1)
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Social network 4', 900, 3, 2)
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Online market 2', 1100, 1, 2)
insert into Project (Name, Cost, ContractorId, GreelancerId) values ('Website 3', 10, 3, 3)